services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./rs-app-be
    restart: always
    environment:
      PGHOST: db
      PGUSER: admin
      PGPASSWORD: password123
      PGDATABASE: rs_db
      PGPORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./rs-app-fe
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
